### PR TITLE
attribute names are strings, objc wants bytes

### PR DESCRIPTION
**Pull request by temoto**
Related issue #6

### CODE REVIEW

**Comment by benregn** [comment]
This is also working for me under Yosemite :package:

**Comment by dbader** [comment]
Thanks @temoto! Looks like this is a fix for Python 3 / Yosemite. Did anybody have a chance to test if this works on 2.7 and on Mountain Lion?

**Comment by benregn** [comment]
@dbader I don't know about Mountain Lion but 2.7 should be fine with this:

```python
Python 2.7.9 (default, Jan 29 2015, 06:27:40)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> b'Testing, testing...'
'Testing, testing...'
>>> 'More testing'.encode()
'More testing'
```

**Comment by dbader** [comment]
Thanks @temoto and @benregn :+1: I'll merge this now and prepare a new release shortly.

**Comment by dbader** [comment]
Released in https://pypi.python.org/pypi/pytest-osxnotify/0.1.6

**Pull request merged**
